name: CI/CD for CrystalPay_Backend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DB_URL: jdbc:postgresql://localhost:5432/testdb
      DB_USERNAME: postgres
      DB_PASSWORD: postgres

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '17'

    - name: Grant execute permission for Gradle wrapper
      run: chmod +x gradlew

    - name: Build and Run Tests
      run: ./gradlew clean build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Deploy to Server
      env:
        SSH_PASS: ${{ secrets.SSH_PASS }}
      run: |
        sshpass -p "$SSH_PASS" ssh -o StrictHostKeyChecking=no crystalpay@172.16.0.20 << 'EOF'
          cd /path/to/CrystalPay_Backend
          git pull origin main
          ./gradlew clean build -x test
          sudo systemctl restart your-service-name
        EOF
